services:
  valkey:
    image: valkey/valkey:9.1.0-alpine
    container_name: valkey_server
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    command: valkey-server --appendonly yes
    restart: always

volumes:
  valkey_data:
